const express = require("express");
const router = express.Router();

const signup = require("../controllers/user/signup.controller");
const login = require("../controllers/user/login.controller");
const authenticateUser = require("../middleware/authenticateUser");
const createPost = require("../controllers/post/post.controller");
const getHomePosts = require("../controllers/post/homePosts.controller");
const profilePosts = require("../controllers/post/profilePosts.controller");
const profileUpload = require("../controllers/post/profileUpload.controller");
const getProfileUser = require("../controllers/user/profileUser.controller");
const getSuggestionUsers = require("../controllers/user/suggestionUsers");
const followUser = require("../controllers/follow/followUser.controller");
const getFollowCount = require("../controllers/follow/followCount.controller");
const storyUpload = require("../controllers/story/storyUpload.controller");
const getHomeStories = require("../controllers/story/homeStory.controller");
const getUserStories = require("../controllers/story/userStories.controller");
const commentPost = require("../controllers/comment/commentPost.controller");
const getComments = require("../controllers/comment/comments.controller");
const likePost = require("../controllers/like/like.controller");
const UnlikePost = require("../controllers/like/unlike.controller");
const likesCount = require("../controllers/like/likesCount.controller");
const likeStatus = require("../controllers/like/status.controller");
const likeCommentCount = require("../controllers/post/likeCommentCount.controller");
const getUserProfile = require("../controllers/post/userProfile.controller");
const userProfilePosts = require("../controllers/post/userProfilePosts.controller");
const searchUsers = require("../controllers/user/searchUsers.controller");
const followStatus = require("../controllers/follow/followStatus.controller");

router.post("/signup", signup);
router.post("/login", login);
router.post("/create-post", authenticateUser, createPost);
router.get("/home-posts", authenticateUser, getHomePosts);
router.get("/profile-posts", authenticateUser, profilePosts);
router.post("/upload-profile", authenticateUser, profileUpload);
router.get("/profile-user", authenticateUser, getProfileUser);
router.get("/search", authenticateUser, searchUsers);
router.get("/posts/:username", authenticateUser, userProfilePosts);
router.get("/suggestion-users", authenticateUser, getSuggestionUsers);
router.post("/follow-user", authenticateUser, followUser);
router.get("/follow-count", authenticateUser, getFollowCount);
router.post("/story-upload", authenticateUser, storyUpload);
router.get("/stories", authenticateUser, getHomeStories);
router.get("/stories/:username", authenticateUser, getUserStories);
router.post("/post-comment", authenticateUser, commentPost);
router.get("/comments/:postId", authenticateUser, getComments);
router.post("/like-post", authenticateUser, likePost);
router.post("/unlike-post", authenticateUser, UnlikePost);
router.get("/likes/:postId", authenticateUser, likesCount);
router.get("/liked-status/:postId", authenticateUser, likeStatus);
router.get("/lc-count/:postId", authenticateUser, likeCommentCount);
router.get("/:username", authenticateUser, getUserProfile);
router.get("/follow-status/:userId", authenticateUser, followStatus);

module.exports = router;
